name: reservation_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  lottie: ^2.3.0
  get: 4.6.5
  sprintf: 7.0.0
  pattern_formatter: 2.0.0
  flutter: 
    sdk: flutter
  excel: ^2.1.0
  path_provider: ^2.0.15
  cloud_firestore: ^4.4.5
  equatable: ^2.0.5
  google_nav_bar: ^5.0.6
  url_launcher: ^6.1.10
  intl: ^0.17.0
  calendar_timeline: ^1.1.2
  time_range: ^1.1.0
  permission_handler: ^10.3.0
  device_info: ^2.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets: 
    - assets/
    - assets/lottie/
  fonts: 
    - family: OpenSansRegular
      fonts: 
        - asset: fonts/OpenSans-Regular.ttf
          style: normal
    - family: OpenSansBold
      fonts: 
        - asset: fonts/OpenSans-Bold.ttf
          style: normal
    - family: OpenSansSemiBold
      fonts: 
        - asset: fonts/OpenSans-SemiBold.ttf
          style: normal

